# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZdRjDakILlM7TINntCsec9LLExU-Bxx6
"""

import numpy as np
import random

# Generate random bits
def generate_bits(n):
    return np.random.randint(0, 2, n)

# Generate random bases
def generate_bases(n):
    return np.random.choice(['X', 'Z'], n)

# Transmission simulation
def transmit(bits, alice_bases, bob_bases):
    bob_results = []

    for i in range(len(bits)):
        if alice_bases[i] == bob_bases[i]:
            bob_results.append(bits[i])
        else:
            bob_results.append(random.randint(0, 1))

    return bob_results

# Generate shared key
def generate_key(alice_bits, alice_bases, bob_bases):
    key = []

    for i in range(len(alice_bits)):
        if alice_bases[i] == bob_bases[i]:
            key.append(alice_bits[i])

    return key

# Encryption
def encrypt(message, key):
    encrypted = ""

    for i in range(len(message)):
        encrypted += chr(ord(message[i]) ^ key[i % len(key)])

    return encrypted

# Decryption
def decrypt(cipher, key):
    decrypted = ""

    for i in range(len(cipher)):
        decrypted += chr(ord(cipher[i]) ^ key[i % len(key)])

    return decrypted

# Display function
def display(alice_bits, alice_bases, bob_bases, bob_results, key):
    print("\nAlice Bits:", alice_bits)
    print("Alice Bases:", alice_bases)

    print("\nBob Bases:", bob_bases)
    print("Bob Results:", bob_results)

    print("\nShared Secret Key:", key)

# Main program
n = 20

alice_bits = generate_bits(n)
alice_bases = generate_bases(n)
bob_bases = generate_bases(n)

bob_results = transmit(alice_bits, alice_bases, bob_bases)

key = generate_key(alice_bits, alice_bases, bob_bases)

display(alice_bits, alice_bases, bob_bases, bob_results, key)

key = [int(i) for i in key]

message = "HELLO"

encrypted = encrypt(message, key)
decrypted = decrypt(encrypted, key)

print("\nOriginal Message:", message)
print("Encrypted Message:", encrypted)
print("Decrypted Message:", decrypted)